# Generated by Django 3.2.8 on 2021-10-28 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='intents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='responseSamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2048)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.responses')),
            ],
        ),
        migrations.CreateModel(
            name='intentSamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2048)),
                ('product_ref', models.IntegerField()),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.intents')),
            ],
        ),
        migrations.CreateModel(
            name='conversationSamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_ref', models.IntegerField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.conversations')),
                ('intent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.intents')),
                ('response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.responses')),
            ],
        ),
    ]
