# Generated by Django 3.2.8 on 2021-10-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentsamples',
            name='product_ref',
            field=models.IntegerField(null=True),
        ),
    ]
