# Generated by Django 3.2.8 on 2021-10-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_trainingmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodels',
            name='insert_time',
            field=models.DateField(auto_now=True),
        ),
    ]
