# Generated by Django 3.2.8 on 2021-10-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_trainingmodels_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodels',
            name='fileCountVect',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='trainingmodels',
            name='fileFitTransform',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trainingmodels',
            name='fileModel',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
