# Generated by Django 3.2.8 on 2021-10-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_auto_20211028_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodels',
            name='acc_train',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trainingmodels',
            name='acc_validate',
            field=models.FloatField(null=True),
        ),
    ]
