# Generated by Django 3.2.8 on 2021-10-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('marca', models.CharField(max_length=256)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField(max_length=2048)),
            ],
        ),
    ]
